### ISSUE TITLE
Update CodeSandbox examples to ^6.0.0

### ISSUE THREAD

**Issue by chanceeakin** [drcmda/react-spring#288]
Current examples are locked in at different versions of 3.x. These should be updated to reflect all of the awesome work that's going on with this lib. 

(Opening this ticket partially for myself...but also for anyone else who feels the urge to help out. 🙃)

**Comment by drcmda** [comment]
would love to receive some help here. i have something in mind like an extra page (in docz) for examples with a small animated gif screencap of something to show what's behind the link. that would be lovely. also of course if tests were a little bit more focussed and better designed but now i'm dreaming.

**Comment by chanceeakin** [comment]
Yeah, I gotcha. I'll see what I can work on. I've got a fork of some of the codepens; will send you something when I have something to send! 😅

**Comment by drcmda** [comment]
Documentation/examples.mdx is now pushed. You could add it there.

**Comment by craftgear** [comment]
Hey, I was just tweaking this example and made it work.

```jsx
import React, { useRef } from 'react';
import { Parallax, ParallaxLayer } from 'react-spring/dist/addons';
import './parallax.css';

const Page = ({ offset, caption, first, second, gradient, onClick }) => (
  <>
    <ParallaxLayer offset={offset} speed={0.2} onClick={onClick}>
      <div className="slopeBegin" />
    </ParallaxLayer>
    <ParallaxLayer offset={offset} speed={-0.2} onClick={onClick}>
      <div className={`slopeEnd ${gradient}`} />
    </ParallaxLayer>
    <ParallaxLayer className="text number" offset={offset} speed={0.3} onClick={onClick}>
      <span>0{offset + 1}</span>
    </ParallaxLayer>
    <ParallaxLayer className="text header" offset={offset} speed={0.4} onClick={onClick}>
      <span>
        <p style={{ fontSize: 20 }}>{caption}</p>
        <div className={`stripe ${gradient}`} />
        <p>{first}</p>
        <p>{second}</p>
      </span>
    </ParallaxLayer>
  </>
);

export default () => {
  let parallax = useRef(null);
  const scroll = to => parallax.scrollTo(to);
  return (
    <div style={{ background: '#dfdfdf' }}>
      <Parallax
        className="container"
        ref={node => (parallax = node)}
        pages={3}
        horizontal
        scrolling={false}
      >
        <Page
          offset={0}
          gradient="pink"
          caption="who we are"
          first="Lorem ipsum"
          second="dolor sit"
          onClick={() => scroll(1)}
        />
        <Page
          offset={1}
          gradient="teal"
          caption="what we do"
          first="consectetur"
          second="adipiscing elit"
          onClick={() => scroll(2)}
        />
        <Page
          offset={2}
          gradient="tomato"
          caption="what we want"
          first="Morbi quis"
          second="est dignissim"
          onClick={() => scroll(0)}
        />
      </Parallax>
    </div>
  );
};
```
```css
.container > div > div {
  display: flex;
  align-items: center;
  justify-content: center;
}

.text {
  pointer-events: none;
  justify-content: start!important;
  font-family: 'Kanit', sans-serif;
  line-height: 0px;
  text-transform: uppercase;
}

.number {
  color: #545864;
}

.number span {
  font-size: 300px;
  display: inline-block;
  position: relative;
  transform: translate3d(5%, 0, 0);
}

.header {
  margin-left: 350px;
  font-size: 70px;
  color: white;
}

.stripe {
  height: 2px;
  width: auto;
}

.slopeBegin {
  background-color: #20232f;
  clip-path: polygon(20% 0, 70% 0, 50% 100%, 0% 100%);
}

.slopeEnd {
  clip-path: polygon(70% 0, 100% 0, 80% 100%, 50% 100%);
}

.slopeBegin,
.slopeEnd {
  position: absolute;
  width: 170%;
  height: 100%;
  cursor: pointer;
}

.pink {
  background: linear-gradient(to right, deeppink 0%, coral 100%);
}

.teal {
  background: linear-gradient(to right, SlateBlue 0%, DeepSkyBlue 100%);
}

.tomato {
  background: linear-gradient(to right, tomato 0%, gold 100%);
}
```
